### ISSUE TITLE
Firebase Json file can be accessed by anyone

### ISSUE THREAD

**Issue by sjmach** [EsdrasRafael/Flutter#1]

**Comment by sjmach** [comment]
https://github.com/EsdrasRafael/Flutter/blob/master/chat_online_firebase/android/app/google-services.json

**Comment by EsdrasRR** [comment]
Hello, I am new and I am making this app as a way of learning, what problems can I have when leaving this public file?

**Comment by sjmach** [comment]
People can use your credentials in nasty ways
